name: Yarn CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:latest # Use an image that suits your project's needs
      options: --user root # Depending on the image, you might need root access to install packages

    steps:
    - uses: actions/checkout@v2

    - name: Install specific Yarn version
      run: npm install -g yarn

    - name: Set yarn berry as the default package manager
      run: yarn set version berry  

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
