name: Yarn CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20 # Use an image that suits your project's needs
      options: --user root # Depending on the image, you might need root access

    steps:
      - uses: actions/checkout@v2

      - name: Prepare .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set yarn berry as the default package manager
        run: yarn set version berry
        # No need to set NPM_TOKEN here as it's not used directly by this command

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Publish to npm
        run: yarn npm publish # Publish the package using Yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
