name: Yarn CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: node:20 # Use an image that suits your project's needs
      options: --user root # Depending on the image, you might need root access

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      # Set yarn npm registry to the public npm registry
      - name: Set npm registry
        run: yarn config set registry '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      # Conditional publish step that only runs on push to main, not on pull requests
      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
