name: Yarn CI/CD

on:
  push:
    branches: [main, "releases/**"]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Recommended to use an LTS version of Node.js
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - name: Install Yarn using Corepack
        run: corepack prepare yarn@4.1.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
