name: Yarn CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20 # Use an image that suits your project's needs
      options: --user root # Depending on the image, you might need root access

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Match this version with your development environment
          cache: "yarn" # Enable Yarn caching

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
