name: Yarn CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: node:20
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      # Correctly set the npm registry for Yarn, ensuring the token is used only when needed
      - name: Configure Yarn for npm registry
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      # Conditional publish step that only runs on push to main, not on pull requests
      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: yarn npm publish --access public
