name: Yarn Publish CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20 # Use an image that suits your project's needs
      options: --user root # Depending on the image, you might need root access to install packages
    env:
      YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version here
          registry-url: "https://registry.npmjs.org/"
          # Yarn 2+ uses YARN_NPM_AUTH_TOKEN instead of NODE_AUTH_TOKEN for authentication
          # with the npm registry.
          cache: "yarn" # Caching dependencies for faster builds

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Publish to npm
        run: yarn npm publish --access public # Ensure you specify the access level if needed
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
